version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "Pukimaa"
    versioning-strategy: auto
